In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import flopy
import flopy.modflow as mf
import flopy.utils as fu
import shutil
import json
import sys

%matplotlib inline

In [2]:
print(sys.version)
print('numpy version: {}'.format(np.__version__))
print('matplotlib version: {}'.format(matplotlib.__version__))
print('flopy version: {}'.format(flopy.__version__))

3.7.1 (default, Nov  6 2018, 18:46:03) 
[Clang 10.0.0 (clang-1000.11.45.5)]
numpy version: 1.15.4
matplotlib version: 3.0.2
flopy version: 3.2.10


In [3]:
central_base_model_path = os.path.join('central-base-model')
cbm = mf.Modflow.load("model.nam", model_ws=central_base_model_path, verbose=False, check=False, exe_name="mf2000")

### Extracting Data from model return wrong results

#### Expecting

In [4]:
fname = os.path.join(central_base_model_path, 'model.bcf')
with open(fname, 'r') as fin:
    print(fin.read())

       154 -1.00e+30         1  1.00e+00         1         0         0
 1 2 0 0 0 0 0
        11  1.00e+00(10G11.4)                   -1 Anisotropy factor(s)
         1.         1.         1.         1.         1.         1.         1.
        11        1. (10G11.4)                  -1 X-Conductivity Layer - 0
         1.         1.         1.         1.         1.         1.         1.         1.         1.         1.
         1.         1.         1.         1.         1.         1.         1.         1.         1.         1.
         1.         1.         1.         1.         1.         1.         1.         1.         1.         1.
         1.         1.         1.         1.         1.         1.         1.         1.         1.         1.
         1.         1.         1.         1.         1.         1.         1.         1.         1.         1.
         1.         1.         1.         1.         1.         1.         1.         1.         1.       1.e3
       1.e3       1.e3

#### Getting

In [5]:
bcf = cbm.bcf6
print(bcf.hy.array)

[[[   1.    1.    1. ... 1000. 1000. 1000.]
  [   1.    1.    1. ... 1000. 1000. 1000.]
  [   1.    1.    1. ... 1000. 1000. 1000.]
  ...
  [   1.    1.    1. ... 1000. 1000. 1000.]
  [   1.    1.    1. ... 1000. 1000. 1000.]
  [   1.    1.    1. ... 1000. 1000. 1000.]]

 [[   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]]

 [[   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]]

 ...

 [[   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...    0.    0.    

### Error loading the file directly

In [6]:
bcf = mf.ModflowBcf.load(os.path.join(central_base_model_path, 'model.bcf'), cbm)

TypeError: 'NoneType' object is not subscriptable